openapi: 3.0.0
info:
  title: API Quote Patrimonial - Open Insurance Brasil
  description: |
    API de Cotação Patrimonial do Open Insurance Brasil - Fase 3.\
    Recebe informações da solicitação de cotação e contratação vindas das instituições iniciadoras.\
    Possui um conjunto de endpoints por ramo de produto e um conjunto específico de endpoints para ramos classificados como LEAD OPIN.\
    Requer consentimento do cliente para todos os 'endpoints'.
    
    # Orientações
    A `Role` do diretório de participantes relacionada à presente API é a `ICS`.\
    Para todos os `endpoints` desta API é previsto o envio de um `token` através do header `Authorization`.\
    Os dados serão entregues pela iniciadora na seguradora desde que o `consentId` relacionado corresponda a um consentimento válido e com o status `AUTHORISED`.\
    Relacionamos a seguir as `permissions` necessárias para o envio de dados em cada `endpoint` da presente API.

    ## Permissions necessárias para a API Quote Patrimonial

    Para cada um dos `paths` desta API, além dos escopos (`scopes`) indicados existem `permissions` que deverão ser observadas:

    ### `/lead/request`
      - permissions:
        - POST: **QUOTE_PATRIMONIAL_LEAD_CREATE**   
    ### `/lead/request/{consentId}`
      - permissions:      
        - PATCH: **QUOTE_PATRIMONIAL_LEAD_UPDATE**
    ### `/home/request/{consentId}/quote-status`
      - permissions:
        - GET: **QUOTE_PATRIMONIAL_HOME_READ**    
    ### `/home/request`
      - permissions:   
        - POST: **QUOTE_PATRIMONIAL_HOME_CREATE**   
    ### `/home/request/{consentId}`
      - permissions:   
        - PATCH: **QUOTE_PATRIMONIAL_HOME_UPDATE**
    ### `/condominium/request/{consentId}/quote-status`
      - permissions:
        - GET: **QUOTE_PATRIMONIAL_CONDOMINIUM_READ**    
    ### `/condominium/request`
      - permissions:   
        - POST: **QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE**   
    ### `/condominium/request/{consentId}`
      - permissions:   
        - PATCH: **QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE**
    ### `/business/request/{consentId}/quote-status`
      - permissions:
        - GET: **QUOTE_PATRIMONIAL_BUSINESS_READ**    
    ### `/business/request`
      - permissions:   
        - POST: **QUOTE_PATRIMONIAL_BUSINESS_CREATE**   
    ### `/business/request/{consentId}`
      - permissions:   
        - PATCH: **QUOTE_PATRIMONIAL_BUSINESS_UPDATE**
    ### `/diverse-risks/request/{consentId}/quote-status`
      - permissions:
        - GET: **QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ**    
    ### `/diverse-risks/request`
      - permissions:   
        - POST: **QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE**   
    ### `/diverse-risks/request/{consentId}`
      - permissions:   
        - PATCH: **QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE**

    ## Válidações Semanticas - Entidade não processável - 422
      - 1 - `Idempotência:` Valida se há divergência entre chave de idempotência e informações enviadas (ERRO_IDEMPOTENCIA);
      - 2 - `Não Informado:` Valida itens não explicitamente informados pelo servidor - (NAO_INFORMADO).   

  version: 1.9.0
  contact:
    name: Governança do Open Insurance Brasil
    url: 'https://www.gov.br/susep'
servers:
  - url: 'https://api.organizacao.com.br/open-insurance/quote-patrimonial/v1'
    description: Servidor de Produção
  - url: 'https://api.organizacao.com.br/open-insurance/quote-patrimonial/v1'
    description: Servidor de Homologação
tags:
  - name: PatrimonialLead
    description: Iniciação de serviços de seguro Cotação Patrimonial (PatrimonialLead)
  - name: PatrimonialHome
    description: Iniciação de serviços de seguro Cotação Patrimonial (PatrimonialHome)
  - name: PatrimonialCondominium
    description: Iniciação de serviços de seguro Cotação Patrimonial (PatrimonialCondominium)
  - name: PatrimonialBusiness
    description: Iniciação de serviços de seguro Cotação Patrimonial (PatrimonialBusiness)
  - name: PatrimonialDiverseRisks
    description: Iniciação de serviços de seguro Cotação Patrimonial (PatrimonialDiverseRisks)
paths:
  /lead/request:
    post:
      tags:
        - PatrimonialLead
      summary: Envia dados de cotação e contratação de PatrimonialLead
      description: "Método para criação de solicitação de cotação e contratação de PatrimonialLead"
      operationId: "postQuotePatrimonialLead"
      security:
        - OAuth2Security:
          - quote-patrimonial-lead
  /lead/request/{consentId}:
    patch:
      tags:
        - PatrimonialLead
      summary: Atualiza dados de cotação e contratação de PatrimonialLead identificado por consentId
      description: "Método para atualização de solicitação de cotação e contratação de PatrimonialLead"
      operationId: "patchQuotePatrimonialLead"
      security:
        - OAuth2Security:
          - quote-patrimonial-lead

  /home/request:
    post:
      tags:
        - PatrimonialHome
      summary: Envia dados de cotação e contratação de PatrimonialHome
      description: "Método para criação de solicitação de cotação e contratação de PatrimonialHome"
      operationId: "postQuotePatrimonialHome"
      security:
        - OAuth2Security:
          - quote-patrimonial-home
  /home/request/{consentId}/quote-status:
    get:
      tags:
        - PatrimonialHome
      summary: Obtém os dados de cotação e contratação de PatrimonialHome identificado por consentId
      description: "Método para consulta dos dados de solicitação de cotação e contratação de PatrimonialHome"
      operationId: "getQuotePatrimonialHome"
      security:
        - OAuth2Security:         
          - quote-patrimonial-home
  /home/request/{consentId}:
    patch:
      tags:
        - PatrimonialHome
      summary: Atualiza dados de cotação e contratação de PatrimonialHome identificado por consentId
      description: "Método para atualização de solicitação de cotação e contratação de PatrimonialHome"
      operationId: "patchQuotePatrimonialHome"
      security:
        - OAuth2Security:          
          - quote-patrimonial-home

  /condominium/request:
    post:
      tags:
        - PatrimonialCondominium
      summary: Envia dados de cotação e contratação de PatrimonialCondominium
      description: "Método para criação de solicitação de cotação e contratação de PatrimonialCondominium"
      operationId: "postQuotePatrimonialCondominium"
      security:
        - OAuth2Security:
          - quote-patrimonial-condominium
  /condominium/request/{consentId}/quote-status:
    get:
      tags:
        - PatrimonialCondominium
      summary: Obtém os dados de cotação e contratação de PatrimonialCondominium identificado por consentId
      description: "Método para consulta dos dados de solicitação de cotação e contratação de PatrimonialCondominium"
      operationId: "getQuotePatrimonialCondominium"
      security:
        - OAuth2Security:         
          - quote-patrimonial-condominium
  /condominium/request/{consentId}:
    patch:
      tags:
        - PatrimonialCondominium
      summary: Atualiza dados de cotação e contratação de PatrimonialCondominium identificado por consentId
      description: "Método para atualização de solicitação de cotação e contratação de PatrimonialCondominium"
      operationId: "patchQuotePatrimonialCondominium"
      security:
        - OAuth2Security:          
          - quote-patrimonial-condominium

  /business/request:
    post:
      tags:
        - PatrimonialBusiness
      summary: Envia dados de cotação e contratação de PatrimonialBusiness
      description: "Método para criação de solicitação de cotação e contratação de PatrimonialBusiness"
      operationId: "postQuotePatrimonialBusiness"
      security:
        - OAuth2Security:
          - quote-patrimonial-business
  /business/request/{consentId}/quote-status:
    get:
      tags:
        - PatrimonialBusiness
      summary: Obtém os dados de cotação e contratação de PatrimonialBusiness identificado por consentId
      description: "Método para consulta dos dados de solicitação de cotação e contratação de PatrimonialBusiness"
      operationId: "getQuotePatrimonialBusiness"
      security:
        - OAuth2Security:         
          - quote-patrimonial-business
  /business/request/{consentId}:
    patch:
      tags:
        - PatrimonialBusiness
      summary: Atualiza dados de cotação e contratação de PatrimonialBusiness identificado por consentId
      description: "Método para atualização de solicitação de cotação e contratação de PatrimonialBusiness"
      operationId: "patchQuotePatrimonialBusiness"
      security:
        - OAuth2Security:          
          - quote-patrimonial-business

  /diverse-risks/request:
    post:
      tags:
        - PatrimonialDiverseRisks
      summary: Envia dados de cotação e contratação de PatrimonialDiverseRisks
      description: "Método para criação de solicitação de cotação e contratação de PatrimonialDiverseRisks"
      operationId: "postQuotePatrimonialDiverseRisks"
      security:
        - OAuth2Security:
          - quote-patrimonial-diverse-risks
  /diverse-risks/request/{consentId}/quote-status:
    get:
      tags:
        - PatrimonialDiverseRisks
      summary: Obtém os dados de cotação e contratação de PatrimonialDiverseRisks identificado por consentId
      description: "Método para consulta dos dados de solicitação de cotação e contratação de PatrimonialDiverseRisks"
      operationId: "getQuotePatrimonialDiverseRisks"
      security:
        - OAuth2Security:         
          - quote-patrimonial-diverse-risks
  /diverse-risks/request/{consentId}:
    patch:
      tags:
        - PatrimonialDiverseRisks
      summary: Atualiza dados de cotação e contratação de PatrimonialDiverseRisks identificado por consentId
      description: "Método para atualização de solicitação de cotação e contratação de PatrimonialDiverseRisks"
      operationId: "patchQuotePatrimonialDiverseRisks"
      security:
        - OAuth2Security:          
          - quote-patrimonial-diverse-risks

components:
  securitySchemes:
    OpenId:
      type: openIdConnect
      openIdConnectUrl: 'https://auth.mockbank.poc.raidiam.io/.well-known/openid-configuration'
    OAuth2Security:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://authserver.example/token"
          scopes:
            quote-patrimonial-lead: Escopo necessário para acesso à API Quote Patrimonial.
            quote-patrimonial-home: Escopo necessário para acesso à API Quote Patrimonial.
            quote-patrimonial-condominium: Escopo necessário para acesso à API Quote Patrimonial.
            quote-patrimonial-business: Escopo necessário para acesso à API Quote Patrimonial.
            quote-patrimonial-diverse-risks: Escopo necessário para acesso à API Quote Patrimonial.
            